dist: trusty
sudo: required

env:
  global:
    - IMAGE=coreos-nvidia-driver
  matrix:
    - COREOS_TRACK=stable OS_VERSION=1235.9.0 NVIDIA_DRIVER_VERSION=390.87 NVIDIA_PRODUCT_TYPE=geforce NVIDIA_SITE=us.download.nvidia.com/XFree86/Linux-x86_64
    - COREOS_TRACK=stable OS_VERSION=current NVIDIA_DRIVER_VERSION=390.87 NVIDIA_PRODUCT_TYPE=geforce NVIDIA_SITE=us.download.nvidia.com/XFree86/Linux-x86_64
    - COREOS_TRACK=stable OS_VERSION=1235.9.0 NVIDIA_DRIVER_VERSION=396.44 NVIDIA_PRODUCT_TYPE=tesla NVIDIA_SITE=us.download.nvidia.com/tesla
    - COREOS_TRACK=stable OS_VERSION=current NVIDIA_DRIVER_VERSION=396.44 NVIDIA_PRODUCT_TYPE=tesla NVIDIA_SITE=us.download.nvidia.com/tesla

before_script:
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/${OS_VERSION}/version.txt -o version.txt
  - cat version.txt
  - export $(cat version.txt | xargs)
  - if [ "$TRAVIS_EVENT_TYPE" != "push" ]; then
      curl -s https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${IMAGE}/tags/?page_size=10000 | 
      jq -e "[.results | .[] | .name == \"${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION}-${NVIDIA_PRODUCT_TYPE}\"] | any | not" || 
      travis_terminate 0;
    fi

script:
  - docker build 
    --build-arg NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION} 
    --build-arg NVIDIA_PRODUCT_TYPE=${NVIDIA_PRODUCT_TYPE} 
    --build-arg NVIDIA_SITE=${NVIDIA_SITE} 
    --build-arg COREOS_VERSION=${COREOS_VERSION} 
    --tag ${DOCKER_USERNAME}/${IMAGE}:${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION}-${NVIDIA_PRODUCT_TYPE}
    .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${DOCKER_USERNAME}/${IMAGE}:${COREOS_VERSION}-${NVIDIA_DRIVER_VERSION}-${NVIDIA_PRODUCT_TYPE}
